### PR TITLE
fix clippy warnings Resolves #62

### LINKED ISSUE #62: Fix clippy

### PR DESCRIPTION
**Pull request by rakurame96**
fixes the clippy & rustdoc warnings

### CODE REVIEW

File: java-bridge/src/lib.rs [hunk 1]
```diff
@@ -64,6 +64,7 @@ static RT: LazyLock<Runtime> = LazyLock::new(|| {
         .unwrap()
 });
 
+#[allow(clippy::type_complexity)]
```
Comment (radumarias) [inline java-bridge/src/lib.rs]: is it still needed if it's added here? https://github.com/radumarias/rencfs/pull/186/files#diff-8fbf9e9b0b12515f84b26e686fd2e8fa9877b4a11348bcfddff2f4e33007f977R69

Comment (rakurame96) [reply java-bridge/src/lib.rs]: Yes. As during build it throws the type complexity error. I can reconfirm once by removing it.

**Review by radumarias — APPROVED** [review]
